---
title: "School Ventilation by NTA"
author: "CityWorkers4Justice"
date: "9/28/2020"
output:
  html_document: 
    toc: TRUE
    toc_depth: 2
  theme: cosmo
runtime: shiny
resource_files:
- global.R
- data/NYC_School_Locations.csv
- output/NYC_Schools_Ventilation_Data.csv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data prep, echo=FALSE, message=FALSE, warning=FALSE}
# rename columns
df <- district_data %>%
  arrange(NTA) %>%
  select(NTA, NTA_Name, contains("perc_")) %>%
  rename("NTA Name" = "NTA_Name",
         "Windows present" = "perc_rooms_windows",
         "Windows that open" = "perc_rooms_windows_open",
         "Supply fan present" = "perc_rooms_supplyFan",
         "Supply fan operational" = "perc_rooms_supplyFan_operational",
         "Supply fan partially operational" = "perc_rooms_supplyFan_partOperational",
         "Supply fan non-operational"  = "perc_rooms_supplyFan_nonOperational",
         "Exhaust fan present" = "perc_rooms_exhaustFan",
         "Exhaust fan operational" = "perc_rooms_exhaustFan_operational",
         "Exhaust fan partially operational" = "perc_rooms_exhaustFan_partOperational",
         "Exhaust fan non-operational" = "perc_rooms_exhaustFan_nonOperational",
         "Ventilation unit present" = "perc_rooms_unitVentilator",
         "Ventilation unit operational" = "perc_rooms_unitVentilator_operational",
         "Ventilation unit partially operational" = "perc_rooms_unitVentilator_partOperational",
         "Ventilation unit non-operational" = "perc_rooms_unitVentilator_nonOperational")

# save mapping data
map_data <- nta_data %>%
  inner_join(df, by = c("nta_id" = "NTA")) %>%
  st_transform(crs = 4326)

# define map theme
theme_map <- function(...) {
  theme_minimal() +
  theme(
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    ...
  )
}
```

# Main Map

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# save vector of variables
ventilation_percentages <- c("Windows present","Windows that open", "Supply fan present", "Supply fan operational", 
                             "Supply fan partially operational", "Supply fan non-operational", "Exhaust fan present",
                             "Exhaust fan operational", "Exhaust fan partially operational", "Exhaust fan non-operational", 
                             "Ventilation unit present", "Ventilation unit operational","Ventilation unit partially operational",
                             "Ventilation unit non-operational")

# add variable selector
selectInput("var","Select Variable to Map", choices = ventilation_percentages)

# save plotting function
map <- reactive({
  ggplot() +
    base_map(st_bbox(map_data), basemap = "positron", increase_zoom = 2, nolabels = TRUE) +
    geom_sf(data = map_data, aes(fill = !!as.symbol(input$var))) +
    theme_map() +
    viridis::scale_fill_viridis("", labels = scales::label_percent(scale = 100), alpha = 0.8) +
    labs(x = NULL, y = NULL, 
         title = "School Building Ventilation Survey", 
         subtitle = paste0(input$var, " (% of total rooms)"),
         caption = "Source: NYC DOE (Data as of October 8, 2020)")
})

# add download handler
downloadHandler(
  filename = function() {paste0("NYC School Ventilation- ", input$var, ".png")},
  content = function(file) {ggsave(file, map())}
)

# render plot
renderPlot({map()})
```

# Bivariate Map

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# add variable selectors
selectInput("covar", "Select Covariate", choices = c("Population living in poverty" = "pop_inpov_pct_est",
                                                     "Non-White population" = "pop_nonwhite_pct_est",
                                                     "Black population" = "pop_black_pct_est",
                                                     "Latinx population" = "pop_hisp_pct_est",
                                                     "White population" = "pop_white_pct_est"))
```

:::: {style="display: grid; grid-template-columns: 1fr 1fr; grid-column-gap: 10px;"}

::: {}

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(biscale)
# save bivariate mapping pipeline
bi_map <- reactive({
  bi_data <- bi_class(map_data, x = !!as.symbol(input$var), 
                      y = !!as.symbol(input$covar), style = "quantile", dim = 3)
  bi_data <- mutate(bi_data, bi_class = ifelse(bi_class == "NA-NA", NA, bi_class))
  
  ggplot() +
    base_map(st_bbox(bi_data), basemap = "dark", increase_zoom = 2, nolabels = TRUE) +
    geom_sf(data = bi_data, mapping = aes(fill = bi_class), color = "lightgrey", size = 0.1, show.legend = FALSE) +
    bi_scale_fill(pal = "DkBlue", dim = 3) +
    theme_map()
})

# save y-axis label name
ylab <- reactive({
  ifelse(input$covar == "pop_inpov_pct_est", "Population living in poverty",
                 ifelse(input$covar == "pop_nonwhite_pct_est", "Non-White population",
                        ifelse(input$covar == "pop_black_pct_est", "Black population",
                               ifelse(input$covar == "pop_hisp_pct_est", "Latinx population",
                                      "White population"))))
})

# save legend pipeline
legend <- reactive({
  # create legend
  bi_legend(pal = "DkBlue", dim = 3, size = 16,
            xlab = paste0(input$var, " (%) "),
            ylab = paste0(ylab(), " (%) "))
})

# add download handler
downloadHandler(
  filename = function() {paste0("NYC School Ventilation- ", input$var, " vs ", ylab(),"- map.png")},
  content = function(file) {ggsave(file, bi_map())}
)

# render map
renderPlot(bi_map())
```

:::

::: {}

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# add download handler
downloadHandler(
  filename = function() {paste0("NYC School Ventilation- ", input$var, " vs ", ylab(),"- legend.png")},
  content = function(file) {ggsave(file, legend())}
)

# render legend
renderPlot(legend())
```

:::

::::

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# save bivariate mapping pipeline
bi_map_single <- reactive({
  bi_data <- bi_class(map_data, x = !!as.symbol(input$var), 
                      y = !!as.symbol(input$covar), style = "quantile", dim = 3)
  bi_data <- mutate(bi_data, bi_class = ifelse(bi_class == "NA-NA", NA, bi_class))
  
  ggplot() +
    base_map(st_bbox(bi_data), basemap = "dark", increase_zoom = 2, nolabels = TRUE) +
    geom_sf(data = bi_data %>% filter(bi_class == "1-3"), 
            mapping = aes(fill = bi_class), color = "lightgrey", size = 0.1, show.legend = FALSE) +
    bi_scale_fill(pal = "DkBlue", dim = 3) +
    theme_map()
})

# add download handler
downloadHandler(
  filename = function() {paste0("NYC School Ventilation- ", input$var, " vs ", ylab(),"- filtered map.png")},
  content = function(file) {ggsave(file, bi_map_single())}
)

# render map
renderPlot(bi_map_single())
```


# Data Table

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# render data table
library(DT)
renderDataTable({
  df %>%
    DT::datatable(rownames = FALSE, extensions = 'Buttons',
                  options = list(scrollX = TRUE,
                                 dom = 'Blfrtip',
                                 buttons = c('copy','csv'),
                                 lengthMenu = list(c(10,25,50,-1),
                                                   c(10,25,50,"All")))) %>%
    DT::formatPercentage(ventilation_percentages, 1)
})
```

